// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AuthLogin: typeof import('./src/components/auth/AuthLogin.vue')['default']
    AuthRegister: typeof import('./src/components/auth/AuthRegister.vue')['default']
    Button: typeof import('./src/components/common/button/button.vue')['default']
    'Icon:bx:bxmoon': typeof import('~icons/bx/bxmoon')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'IconMaterialSymbols:fastfood': typeof import('~icons/material-symbols/fastfood')['default']
    'IconMaterialSymbols:logout': typeof import('~icons/material-symbols/logout')['default']
    'IconMaterialSymbols:restaurantMenu': typeof import('~icons/material-symbols/restaurant-menu')['default']
    'IconMaterialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    'IconMaterialSymbols:settings': typeof import('~icons/material-symbols/settings')['default']
    'IconMaterialSymbols:spaceDashboard': typeof import('~icons/material-symbols/space-dashboard')['default']
    'IconMaterialSymbols:spaceDashboardRounded': typeof import('~icons/material-symbols/space-dashboard-rounded')['default']
    'IconMdi:chefHat': typeof import('~icons/mdi/chef-hat')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpBanner: typeof import('./src/components/common/container/SpBanner.vue')['default']
    SpButton: typeof import('./src/components/common/button/SpButton.vue')['default']
    SpConfirmationButton: typeof import('./src/components/common/button/SpConfirmationButton.vue')['default']
    SpHeader: typeof import('./src/components/common/layout/SpHeader.vue')['default']
    SpImg: typeof import('./src/components/common/container/SpImg.vue')['default']
    SpInput: typeof import('./src/components/common/form/SpInput.vue')['default']
    SpProductCard: typeof import('./src/components/common/card/SpProductCard.vue')['default']
    SpSideMenu: typeof import('./src/components/common/layout/SpSideMenu.vue')['default']
    SpTitle: typeof import('./src/components/common/text/SpTitle.vue')['default']
  }
}
